# 复制该模板文件，重命名为config.yaml
base_url: "http://192.168.1.100:8080"
mysql:
  host: ${MYSQL_HOST}
  port: ${MYSQL_PORT}
  options: "charset=utf8mb4&parseTime=True&loc=Local"
  dbname: "douyin"
  username: ${MYSQL_USER}
  password: ${MYSQL_PASSWORD}
oss:
  endpoint: "oss-cn-hangzhou.aliyuncs.com"
  bucket_name: "stickit-douyin"
  access_key_id: "************************"
  access_key_secret: "******************************"
