# 复制该模板文件，重命名为 config.yaml
# 若值为某个键的路径（点替换为下划线），则会替换为对应的环境变量。
# 例如，对于 mysql.host，值为 MYSQL_HOST，会从环境变量中获取 MYSQL_HOST 的值。
# 若环境变量与键路径不同，可以使用 ${ENV:default}，最终会替换为环境变量中的值。
# 如果环境变量为空，则使用 default 的值。
release: false
mysql:
  host: MYSQL_HOST
  port: MYSQL_PORT
  username: ${MYSQL_USER}
  password: MYSQL_PASSWORD
  options: "charset=utf8mb4&parseTime=True&loc=Local"
  dbname: "douyin"
storage:
  local:
    path: "public"
    base_url: ${paas_url:"http://192.168.1.100:8080"}
  oss:
    enable: false
    endpoint: "oss-cn-hangzhou.aliyuncs.com"
    bucket_name: "stickit-douyin"
    access_key_id: "************************"
    access_key_secret: "******************************"
